package com.example.cst438_project1;

import android.content.Context;

import androidx.room.Room;

import org.junit.Test;

import java.nio.charset.Charset;
import java.util.Random;
import androidx.test.platform.app.InstrumentationRegistry;

import com.example.cst438_project1.DB.StudentAppDatabase;
import com.example.cst438_project1.Objects.User;

import static org.junit.Assert.*;

/*Checks that DAO operations for User work.
 *@author Joshua Click
 */
public class UserDAOTest{
    /*Checks that User can be created and saved to Room
     */
    @Test
    public void UserCreate(){
        Context c = InstrumentationRegistry.getInstrumentation().getContext();
        StudentAppDatabase db = Room.inMemoryDatabaseBuilder(c, StudentAppDatabase.class).build();

        User test = new User("username", "bob", "password");
        db.getUserDao().insertUser(test);
        assertNotNull( db.getUserDao().getUser(test.getName()));

        test = db.getUserDao().getUser(test.getName());

        assertNotNull( db.getUserDao().getUser(test.getID()));
    }
    /*Checks that User can be deleted from Room
     */
    @Test
    public void UserDelete(){
        Context c = InstrumentationRegistry.getInstrumentation().getContext();
        StudentAppDatabase db = Room.inMemoryDatabaseBuilder(c, StudentAppDatabase.class).build();

        User test = new User("username", "bob", "password");
        db.getUserDao().insertUser(test);

        //updates 'test' wth autogenerated userID
        test = db.getUserDao().getUser(test.getName());

        assertNotNull(db.getUserDao().getUser(test.getName()));

        db.getUserDao().deleteUser(test);
        assertNull(db.getUserDao().getUser(test.getName()));
    }
    /*Checks that User can be updated in Room
     */
    @Test
    public void UserUpdate(){
        Context c = InstrumentationRegistry.getInstrumentation().getContext();
        StudentAppDatabase db = Room.inMemoryDatabaseBuilder(c, StudentAppDatabase.class).build();

        User test = new User("username", "bob", "password");
        db.getUserDao().insertUser(test);
        assertNotNull(db.getUserDao().getUser(test.getName()));

        //Generate a random string/"name"
        Random r = new Random();
        byte[] b = new byte[10];
        r.nextBytes(b);
        String name = new String(b, Charset.forName("UTF-8"));

        test = db.getUserDao().getUser(test.getName());

        test.setName(name);
        db.getUserDao().updateUser(test);
        assertEquals(name, db.getUserDao().getUser(test.getID()).getName());
    }
}
